### ISSUE TITLE
error fix please

### ISSUE THREAD

**Issue by LeePC** [timing1337/mineplex-reborn#1]
[12:26:16 ERROR]: Error occurred while enabling Arcade v0.1 (Is it up to date?)
java.lang.NullPointerException: null
        at mineplex.core.common.util.UtilServer.isTestServer(UtilServer.java:161) ~[?:?]
        at mineplex.core.common.util.UtilServer.isTestServer(UtilServer.java:156) ~[?:?]
        at mineplex.core.command.CommandCenter.<init>(CommandCenter.java:101) ~[?:?]
        at mineplex.core.command.CommandCenter.Initialize(CommandCenter.java:84) ~[?:?]
        at nautilus.game.arcade.Arcade.onEnable(Arcade.java:105) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:264) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

![Screenshot_1](https://github.com/timing1337/mineplex-reborn/assets/8704225/19c3d5dd-b79a-457e-9638-6ed0cf893271)

**Comment by LeePC** [comment]
webServer: http://127.0.0.1:1000/

There is only this option

**Comment by LeePC** [comment]
[20:07:33 INFO]: Server Configuration> Initializing...
[20:07:33 INFO]: Server Configuration> Enabled in 0.0 Seconds.
[20:07:33 ERROR]: Error occurred while enabling Arcade v0.1 (Is it up to date?)
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_202]
        at java.lang.Integer.valueOf(Unknown Source) ~[?:1.8.0_202]
        at mineplex.serverdata.data.ServerGroup.<init>(ServerGroup.java:79) ~[?:?]
        at mineplex.serverdata.redis.RedisServerRepository.getServerGroup(RedisServerRepository.java:362) ~[?:?]
        at mineplex.core.serverConfig.ServerConfiguration.<init>(ServerConfiguration.java:43) ~[?:?]
        at nautilus.game.arcade.Arcade.onEnable(Arcade.java:124) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:264) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by LeePC** [comment]
The Hub.jar plugin works
But Arcade.Jar plugin doesn't work

**Comment by petethepossum** [comment]
> The Hub.jar plugin works
> 
> But Arcade.Jar plugin doesn't work

You need to make sure you specify server type in the arcade plugin config
