### ISSUE TITLE
error.......

### ISSUE THREAD

**Issue by LeePC** [timing1337/mineplex-reborn#4]
[11:50:32 INFO]: NpcManager> Initializing...
[11:50:32 INFO]: NpcManager> Enabled in 0.0 Seconds.
[11:50:32 ERROR]: Error occurred while enabling Arcade v0.1 (Is it up to date?)
java.util.ConcurrentModificationException: null
        at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_202]
        at mineplex.core.npc.NpcManager.<init>(NpcManager.java:135) ~[?:?]
        at nautilus.game.arcade.Arcade.onEnable(Arcade.java:140) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:264) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

[latest.log](https://github.com/timing1337/mineplex-reborn/files/14467828/latest.log)

After resolving redis, the next error is displayed

**Comment by petethepossum** [comment]
I’m pretty sure this is a SQL error in the npc and newnpctable, could be wrong though
